package org.firstinspires.ftc.teamcode.helpers;

public enum GameState {
    INITIAL,
    DETECT_BARCODE,
    DRIVE_TO_ALLIANCE_HUB_ONE,
    DRIVE_TO_ALLIANCE_HUB_TWO,
    DRIVE_TO_ALLIANCE_HUB_THREE,
    DRIVE_TO_ALLIANCE_HUB_FOUR,
    DRIVE_TO_ALLIANCE_HUB_FIVE,
    DRIVE_TO_ALLIANCE_HUB_SIX,
    PLACE_CUBE,
    DRIVE_TO_CAROUSEL_ONE,
    DRIVE_TO_CAROUSEL_TWO,
    SPIN_CAROUSEL,
    PARK_IN_DEPOT_ONE,
    PARK_IN_DEPOT_TWO,
    PARK_IN_DEPOT_THREE,
    PARK_IN_WAREHOUSE_ONE,
    PARK_IN_WAREHOUSE_TWO,
    COMPLETE;
}